# -*- coding: utf-8 -*-
"""Main Code_Auto Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x4jFUOXePRLFf15S4BBhkb4b1LgQVqk0
"""

pip install schedule

import re
import time
import random
import numpy as np
import requests as rq

url = 'https://docs.google.com/forms/d/e/1FAIpQLSd2l7DhzyP8IxChVyAEj87YFumAXV0UnoVSMm5t7rehZ8aCdg/formResponse'
params_m=['早上']
params_n=['晚上']

payload = {
    'entry.1013554951': '',
    'entry.232514679':'',
    'entry.43007525': '',
    'entry.303761663': '',
    'fvv': '1',
    'draftResponse': '[]',
    'pageHistory': '0',
    'fbzx': '-8694521782655753776',
}

params_1=['否']
params_2=['是']

payload2 = {
    'entry.1257837995': '',
    'entry.1193263501':'',
    'fvv': '1',
    'draftResponse': '[]',
    'pageHistory': '0,1',
    'fbzx': '-2190249997316525326',
}


from datetime import datetime
import time
import schedule


#period = np.arange(36.0 ,36.5 , 0.1)
period = ['35.8','35.9','36.0','36.1','36.2','36.3','36.4','36.5']
delay = 0  # delay of execution

#try:
aaa=input('你的學號:')
bbb=input('你想說的話:')

def job1():
      payload['entry.1013554951'] = str(aaa), # random choice
      payload['entry.232514679'] = random.choice(period) , # random choice
      payload['entry.43007525'] = str(bbb) ,
      payload['entry.303761663'] = random.choice(params_m),
      res = rq.post(url, data=payload)
      res.raise_for_status()

def job2():
      payload['entry.1013554951'] = str(aaa) , # random choice
      payload['entry.232514679'] = random.choice(period) , # random choice
      payload['entry.43007525'] = str(bbb) ,
      payload['entry.303761663'] = random.choice(params_n) , # random choice ######

      payload2['entry.1257837995'] = random.choice(params_1) ,
      payload2['entry.1193263501'] = random.choice(params_2) ,

      res = rq.post(url, data=payload)
      res = rq.post(url, data=payload2)

#except rq.HTTPError:
   # print('HTTP Error!')
   # num -= 1

# 每隔5秒執行一次job1
def job5():
  schedule.every(5).seconds.do(job1)
# 每天9:30執行任務
#def job3():
#  schedule.every().day.at('05:29').do(job1)   #因為位在+8，所以時區需要-8
#def job4():
#  schedule.every().day.at('05:30').do(job2)   #因為位在+8，所以時區需要-8
if __name__ == "__main__":
#     job3()
#     job4()
     job5()

while True:
      schedule.run_pending()
      time.sleep(1)